### ISSUE TITLE
Getting Started documentation is incomplete

### ISSUE THREAD

**Issue by santanche** [datasci4health/case-notebook#10]
It is not clear what is possible to do in the "Using mybinder.org" version (just runs Jupyter?).
The "Running Locally" instructions are incomplete (they refer to the Jupyter installation?).

**Comment by santanche** [comment]
I adapted the documentation indicating that the Jupyter is used to run the \[basics\] directory examples.

**Comment by matheusmota** [comment]
Please check #11 and reopen the issue if more info is needed
