### ISSUE TITLE
Unfinished/broken cases should be removed

### ISSUE THREAD

**Issue by matheusmota** [datasci4health/case-notebook#12]
Since some cases are not done or are broken, we should remove them. 

Maybe we could leave just one or two good cases as default, since we will be sharing, for instance, links to our cloud elsewhere. Users may select broken cases when trying the tool, resulting in bad experience.

**Comment by marcosfmmota** [comment]
I deleted most of the broken cases in the dev branch but there is one (case003-zombie-health) that I didn't delete because it is finished from the older version perspective.
